### ISSUE TITLE
Error in prepare_files

### ISSUE THREAD

**Issue by sqreb** [vlink/marge#4]
I am trying to use MARGE to analyze ChIP-seq data. When I ran into the steps of prepare_files, I ran into a problem. In this step , I want to be able to generate personal mutations and genomic information. But when I run MARGE as follow, the mutation filename is like "chrchr1_allele_1.mut", and can not generate personal genome files.
<code>MMARGE.pl prepare_files -files Chip/MMARGE/ind_variation/SAMN01731493.sort.vcf -core 28 -ind SAMN01731493 -dir Chip/MMARGE/ind_mutation/SAMN01731493 -genome_dir Chip/MMARGE/ind_genome/SAMN01731493 -genome /home/wangdehe/common/UCSC/genome/split/hg19 -force</code>

Error information
Generating chromosome 1
Done
Chip/MMARGE/ind_mutation/SAMN01731493/SAMN01731493/chr1_allele_1.mut does not exist - go to next strain

**Comment by vlink** [comment]
Hi Dehe, 

does your vcf file name the chromosomes chr1 in the very first column of the file?

Thanks, 
Verena
