### ISSUE TITLE
error during prepare_files

### ISSUE THREAD

**Issue by msubirana** [vlink/marge#7]
I am trying to use mmarge in a human chip-seq using a set of somatic mutations in the same sample to analyse the motif in them. But I got the following error:

```
(mmarge-1.0-env) bash-4.2$ MMARGE.pl prepare_files -files $vcf -core 12 -genome $genome -force -no-genome -add -ind NET10_TI,NET10_BL -dir $dir -genome_dir $genome_dir
Using multithreading for IO writing
Checking if /gpfs42/robbyfs/scratch/lab_lpasquali/msubirana/marc/insulinomas/mmarge_prove/NET10_TI_BL_sorted.vcf is sorted by chromosome and position.
This make take a while.
If you want to skip this step, restart with -no-check. If the file is not sorted, output files are overwritten.

File /gpfs42/robbyfs/scratch/lab_lpasquali/msubirana/marc/insulinomas/mmarge_prove/NET10_TI_BL_sorted.vcf is sorted.

None of the individuals you specified is in the VCF files!
Here are all individuals specified in the header of your file:
	NET10_TI
	NET10_BL
Processing all individuals in 5 seconds
Print Ctrl + C to abort
.....
Starting to process all individuals
Reading in file /gpfs42/robbyfs/scratch/lab_lpasquali/msubirana/marc/insulinomas/mmarge_prove/NET10_TI_BL_sorted.vcf
Merge files and mutations!
Reading in file and caching!
Status: 100% Completed

Processing NET10_TI
		chromosome chr1 allele 1
Can't open /gpfs42/robbyfs/scratch/lab_lpasquali/msubirana/marc/insulinomas/mmarge_prove/dir/NET10_TI/chrchr1_allele_1.mut: No such file or directory
```

**Comment by vlink** [comment]
Hi, 

It seems that in your VCF file the chromosomes are not labeled as 1, 2, 3 etc. but chr1, chr2, chr3 etc. which I think might cause this error.
Could you reformat your VCF file and try again?

**Comment by msubirana** [comment]
Ok thanks! I will take a look. 

Another question. I already called the h3k27ac peaks of my chip data. Can it be possible to use mmarge in these peaks and using a vcf for analyzing differential motif between mutated and wildtype?

**Comment by msubirana** [comment]
yes, you are right, vcf file has the chr labeled as 1,2,3

**Comment by msubirana** [comment]
I removed 'chr' from VCF but I still got an error:

```
Processing NET10_TI
		chromosome 1 allele 1
Can't open /gpfs42/robbyfs/scratch/lab_lpasquali/msubirana/marc/insulinomas/mmarge_prove/dir/NET10_TI/chr1_allele_1.mut: No such file or directory
```

**Comment by msubirana** [comment]
Ok my vcf contained TUMOR and CTRL samples, I removed CTRL column (that was empty and now it works)

What do you thing about:

I already called the h3k27ac peaks of my chip data. Can it be possible to use mmarge in these peaks and using a vcf for analyzing differential motif between mutated and wildtype?

**Comment by vlink** [comment]
yes that is the main usage for MMARGE. After you prepared the genomes and mutation files, you can run mutation_analysis for this. If you have any more questions regarding how to run the pipeline, you can email me directly: verena.m.link@gmail.com
