### ISSUE TITLE
No reads in Output of MMARGE.pl allele_specific_reads

### ISSUE THREAD

**Issue by njwehi** [vlink/marge#8]
Hi,

I found No reads in Output of MMARGE.pl allele_specific_reads

samtools view 

it was data from F1 mice

I run:

MMARGE.pl allele_specific_reads -files S1_shifted_from_CAST_EIJ.sam -ind CAST_EIJ 

shown:
###
Read in mutations
        for chromosome10 - allele 1
        for chromosome11 - allele 1
        for chromosome12 - allele 1
        for chromosome13 - allele 1
        for chromosome14 - allele 1
        for chromosome15 - allele 1
        for chromosome16 - allele 1
        for chromosome17 - allele 1
        for chromosome18 - allele 1
        for chromosome19 - allele 1
        for chromosome1 - allele 1
        for chromosome2 - allele 1
        for chromosome3 - allele 1
        for chromosome4 - allele 1
        for chromosome5 - allele 1
        for chromosome6 - allele 1
        for chromosome7 - allele 1
        for chromosome8 - allele 1
        for chromosome9 - allele 1
        for chromosomeX - allele 1
Processing sam file
S1_shifted_from_CAST_EIJ.sam
###

the -ind files were generated by myself with mm39 as reference.

**Comment by vlink** [comment]
Hi, 

Sorry for the late response. Can you send me your input file so I can test it?

**Comment by vlink** [comment]
Just a general note. The default mapping method for this script is bowtie, so if you used STAR, you need to specify this with -method star. That might explain why you did not get any outputs from your command.

**Comment by njwehi** [comment]
Hi 
Thanks so much for your response and so sorry that I forgot to prepare the input files. here I attached the sam file and the mutation files. Because of the size limitation, I only included data of chr16

Thanks very much!

[CAST_mut.tar.gz](https://github.com/user-attachments/files/16569421/CAST_mut.tar.gz)
d the mutation files.
[test.sam.gz](https://github.com/user-attachments/files/16569388/test.sam.gz)
