### ISSUE TITLE
Issue with prepare_files vcf file sorting

### ISSUE THREAD

**Issue by krovi137** [vlink/marge#9]
Hello,

I am attempting to use MMARGE for analyzing ATAC-seq data from different strains of mice. I downloaded the SNP and Indel vcf files from the Mouse Genomes Project website and sorted them using bcftools sort. However, I keep receiving an error when I use prepare_files that says the vcf file is not sorted:

grep: write error: Broken pipe
File Sorted_SNPs.vcf is not sorted!
Please sort file!
grep "^#" Sorted_SNPs.vcf > sorted file
grep -v "^#" Sorted_SNPs.vcf | sort -k1,1 -k2,2n >> sorted file

I also sorted the file as described using the grep command but that does not seem to get rid of the error. I've also attempted to run the prepare_files command with the -no-check flag but even with that, it checks to see if the vcf files are sorted. Please help!!

Thanks so much!
Harsha

**Comment by vlink** [comment]
Hi, 

Can you send me the link to the files you downloaded, so I can debug it?

Thanks!

**Comment by krovi137** [comment]
Hi! Thanks so much for your response!

Here's the link I used:  https://www.mousegenomes.org/snps-indels/

I downloaded the SNPs/Indels for mm39. Please let me know if you need anything else from me.

Thanks again!

**Comment by krovi137** [comment]
Hello,

I was wondering if you had had a chance to look into the bug perhaps? Please let me know.

Thanks so much!

**Comment by vlink** [comment]
Hi, 

Sorry I finally found time to look into this issue. Could you send me the exact command you used?

**Comment by krovi137** [comment]
Hello,

Sorry for the delayed response. I was able to fix the original problem actually. The issue was that I was using the normal vcf file but I should have been using the rsID file. That was able to resolve the problem.

Thanks for your help!
